---
- name: Install packages
  tags: ad_member
  package:
    name: "{{ ad_member_sssd_packages + ad_member_realmd_packages + ad_member_pam_packages }}"
    state: present

# TODO option to use a configuration template
#- name: Install sssd conf
#  tags: ad_member
#  template:
#    src: "{{ ansible_distribution|lower }}_sssd.conf.j2"
#    dest: "{{ ad_member_sssd_config_file }}"
#    owner: root
#    group: root
#    mode: '0600'
#  notify:
#    - sssd restart
#XXX Joining the domain will create an sssd config with reasonable defaults

- name: Join to the domain
  tags: ad_member
  # do not log to preserve password secrecy
  no_log: True
  shell: "realm join -v --user {{ ad_member_kerberos_user }} --one-time-password={{ ad_member_kerberos_pass }} --os-name={{ ansible_distribution }} --os-version={{ ansible_distribution_version }} {{ ad_member_domain }}"
  notify:
    - sssd restart

- name: Set the user's homedir path
  tags: ad_member
  lineinfile:
    path: "{{ ad_member_sssd_config_path }}"
    regexp: '^\s*fallback_homedir\s*=.*'
    insertafter: "^[domain/{{ ad_member_domain_l }}]"
    line: "fallback_homedir = {{ ad_member_sssd_fallback_homedir }}"
    state: present
  notify:
    - sssd restart

- name: Enable PAM automatic homedir creation
  when: ad_member_automatic_homedir_creation
  tags: ad_member
  shell: "pam-auth-update --enable mkhomedir"

# restart services so test gets up to date config
- meta: flush_handlers

- name: Query AD user
  tags: ad_member
  command: "id -u {{ ad_member_test_user }}"
  register: ad_member_user_query
  when: "ad_member_test_user is defined and ad_member_test_user_uid is defined"
  changed_when: false

- name: Test join was successful
  tags: ad_member
  when: "ad_member_test_user is defined and ad_member_test_user_uid is defined"
  assert:
    that:
      - "ad_member_test_user_uid in ad_member_user_query.stdout"
  ignore_errors: "{{ ansible_check_mode }}"
