---
- name: Include kerberos task
  include_tasks: kerberos.yml
  tags: ad_member

- name: Join to the domain
  tags: ad_member
  # do not log to preserve password secrecy
  no_log: True
  shell: "net ads join -k -U {{ ad_kerberos_user }}%{{ ad_kerberos_pass }} osName={{ ansible_distribution }} osVer={{ ansible_distribution_version }}"
  notify:
    - sssd restart
