---
- name: sssd restart
  service:
    name: "{{ ad_sssd_service_name }}"
    state: restarted

- name: samba reload config
  shell: "smbcontrol smbd reload-config"

- name: samba restart
  service:
    name: "{{ ad_samba_service_name }}"
    state: restarted

- name: winbind restart
  service:
    name: "{{ ad_winbind_service_name }}"
    state: restarted
